// Travel-gateway layers — airports, train stations and seaports — discovery
// aids answering "where can I travel to/from here?". Airports come from the
// OurAirports public-domain dataset (see transport-airports.ts, ~1.2k major
// airports); stations and ports are curated lists of the world's principal
// hubs. The marker layers are off by default and the flat map clusters dense
// areas, so the density stays usable and the globe's frame budget stays safe.
//
// Each point carries an explicit `wiki` article title: many hubs are named
// after people (Jomo Kenyatta, O. R. Tambo, Mohammed V…), so fetching by the
// short display name would surface the person's article, not the place's.
import { AIRPORTS } from "./transport-airports"

export type TransportKind = "airport" | "station" | "port"
export type LayerId = "airports" | "stations" | "ports"

export type TransportPoint = {
  kind: TransportKind
  name: string
  code?: string // IATA for airports; many stations/ports have none
  city: string
  country: string
  lat: number
  lng: number
  wiki: string // exact Wikipedia article title
}

const STATIONS: TransportPoint[] = [
  ["Gare du Nord", "Paris", "France", 48.8809, 2.3553, "Gare du Nord"],
  ["Gare de Lyon", "Paris", "France", 48.8443, 2.3744, "Gare de Lyon"],
  [
    "Gare Montparnasse",
    "Paris",
    "France",
    48.8404,
    2.3199,
    "Gare Montparnasse",
  ],
  ["Gare de l'Est", "Paris", "France", 48.8767, 2.359, "Gare de l'Est"],
  [
    "Gare Saint-Lazare",
    "Paris",
    "France",
    48.8757,
    2.3253,
    "Gare Saint-Lazare",
  ],
  [
    "Lyon Part-Dieu",
    "Lyon",
    "France",
    45.7605,
    4.8595,
    "Lyon-Part-Dieu station",
  ],
  [
    "Marseille Saint-Charles",
    "Marseille",
    "France",
    43.3025,
    5.3804,
    "Gare de Marseille-Saint-Charles",
  ],
  ["Lille Europe", "Lille", "France", 50.639, 3.0755, "Gare de Lille-Europe"],
  [
    "St Pancras International",
    "London",
    "United Kingdom",
    51.532,
    -0.1264,
    "St Pancras railway station",
  ],
  [
    "King's Cross",
    "London",
    "United Kingdom",
    51.5308,
    -0.1238,
    "London King's Cross railway station",
  ],
  [
    "London Waterloo",
    "London",
    "United Kingdom",
    51.5031,
    -0.1132,
    "Waterloo station",
  ],
  [
    "London Paddington",
    "London",
    "United Kingdom",
    51.5154,
    -0.1755,
    "London Paddington station",
  ],
  [
    "London Victoria",
    "London",
    "United Kingdom",
    51.4952,
    -0.1441,
    "London Victoria station",
  ],
  [
    "London Euston",
    "London",
    "United Kingdom",
    51.5282,
    -0.1337,
    "Euston railway station",
  ],
  [
    "Liverpool Street",
    "London",
    "United Kingdom",
    51.5179,
    -0.0823,
    "Liverpool Street station",
  ],
  [
    "Berlin Hauptbahnhof",
    "Berlin",
    "Germany",
    52.5251,
    13.3694,
    "Berlin Hauptbahnhof",
  ],
  [
    "Frankfurt Hauptbahnhof",
    "Frankfurt",
    "Germany",
    50.107,
    8.6638,
    "Frankfurt (Main) Hauptbahnhof",
  ],
  [
    "München Hauptbahnhof",
    "Munich",
    "Germany",
    48.1402,
    11.5586,
    "München Hauptbahnhof",
  ],
  [
    "Hamburg Hauptbahnhof",
    "Hamburg",
    "Germany",
    53.5528,
    10.0067,
    "Hamburg Hauptbahnhof",
  ],
  [
    "Köln Hauptbahnhof",
    "Cologne",
    "Germany",
    50.943,
    6.9588,
    "Köln Hauptbahnhof",
  ],
  [
    "Stuttgart Hauptbahnhof",
    "Stuttgart",
    "Germany",
    48.7841,
    9.182,
    "Stuttgart Hauptbahnhof",
  ],
  [
    "Roma Termini",
    "Rome",
    "Italy",
    41.9009,
    12.5018,
    "Roma Termini railway station",
  ],
  [
    "Milano Centrale",
    "Milan",
    "Italy",
    45.4869,
    9.2042,
    "Milano Centrale railway station",
  ],
  [
    "Madrid Atocha",
    "Madrid",
    "Spain",
    40.4068,
    -3.6895,
    "Madrid Atocha railway station",
  ],
  [
    "Barcelona Sants",
    "Barcelona",
    "Spain",
    41.3792,
    2.1402,
    "Barcelona Sants railway station",
  ],
  [
    "Sevilla Santa Justa",
    "Seville",
    "Spain",
    37.3919,
    -5.9756,
    "Sevilla-Santa Justa railway station",
  ],
  [
    "Amsterdam Centraal",
    "Amsterdam",
    "Netherlands",
    52.3791,
    4.9003,
    "Amsterdam Centraal station",
  ],
  [
    "Bruxelles-Midi",
    "Brussels",
    "Belgium",
    50.8358,
    4.3361,
    "Brussels-South railway station",
  ],
  [
    "Bruxelles-Central",
    "Brussels",
    "Belgium",
    50.8456,
    4.3571,
    "Brussels-Central railway station",
  ],
  [
    "Zürich Hauptbahnhof",
    "Zurich",
    "Switzerland",
    47.3779,
    8.5403,
    "Zürich Hauptbahnhof",
  ],
  [
    "Genève-Cornavin",
    "Geneva",
    "Switzerland",
    46.2103,
    6.1424,
    "Genève-Cornavin railway station",
  ],
  [
    "Wien Hauptbahnhof",
    "Vienna",
    "Austria",
    48.185,
    16.3754,
    "Wien Hauptbahnhof",
  ],
  ["Lisboa Oriente", "Lisbon", "Portugal", 38.7676, -9.0993, "Gare do Oriente"],
  [
    "Stockholm Central",
    "Stockholm",
    "Sweden",
    59.33,
    18.0586,
    "Stockholm Central Station",
  ],
  [
    "København H",
    "Copenhagen",
    "Denmark",
    55.6727,
    12.5641,
    "Copenhagen Central Station",
  ],
  [
    "Moskovsky",
    "Saint Petersburg",
    "Russia",
    59.9286,
    30.3625,
    "Moskovsky railway station",
  ],
  [
    "Leningradsky",
    "Moscow",
    "Russia",
    55.7766,
    37.6549,
    "Leningradsky railway station",
  ],
  ["Tokyo Station", "Tokyo", "Japan", 35.6812, 139.7671, "Tokyo Station"],
  ["Shinjuku Station", "Tokyo", "Japan", 35.6896, 139.7006, "Shinjuku Station"],
  ["Shibuya Station", "Tokyo", "Japan", 35.658, 139.7016, "Shibuya Station"],
  ["Ueno Station", "Tokyo", "Japan", 35.7141, 139.7774, "Ueno Station"],
  ["Osaka Station", "Osaka", "Japan", 34.7025, 135.4959, "Osaka Station"],
  ["Kyoto Station", "Kyoto", "Japan", 34.9858, 135.7588, "Kyoto Station"],
  ["Nagoya Station", "Nagoya", "Japan", 35.1709, 136.8815, "Nagoya Station"],
  ["Seoul Station", "Seoul", "South Korea", 37.5559, 126.9723, "Seoul Station"],
  [
    "Beijing South",
    "Beijing",
    "China",
    39.865,
    116.3786,
    "Beijing South railway station",
  ],
  [
    "Shanghai Hongqiao",
    "Shanghai",
    "China",
    31.1943,
    121.3203,
    "Shanghai Hongqiao railway station",
  ],
  [
    "Guangzhou South",
    "Guangzhou",
    "China",
    22.9905,
    113.267,
    "Guangzhounan railway station",
  ],
  [
    "Hong Kong West Kowloon",
    "Hong Kong",
    "Hong Kong",
    22.3036,
    114.1614,
    "Hong Kong West Kowloon railway station",
  ],
  [
    "Taipei Main Station",
    "Taipei",
    "Taiwan",
    25.0478,
    121.517,
    "Taipei Main Station",
  ],
  [
    "KL Sentral",
    "Kuala Lumpur",
    "Malaysia",
    3.134,
    101.6865,
    "Kuala Lumpur Sentral railway station",
  ],
  [
    "New Delhi",
    "Delhi",
    "India",
    28.6429,
    77.2191,
    "New Delhi railway station",
  ],
  [
    "Chhatrapati Shivaji Terminus",
    "Mumbai",
    "India",
    18.9398,
    72.8355,
    "Chhatrapati Shivaji Maharaj Terminus",
  ],
  [
    "Howrah Junction",
    "Kolkata",
    "India",
    22.5839,
    88.3425,
    "Howrah Junction railway station",
  ],
  [
    "Grand Central Terminal",
    "New York",
    "United States",
    40.7527,
    -73.9772,
    "Grand Central Terminal",
  ],
  [
    "Pennsylvania Station",
    "New York",
    "United States",
    40.7506,
    -73.9935,
    "Pennsylvania Station (New York City)",
  ],
  [
    "Union Station",
    "Washington, D.C.",
    "United States",
    38.8977,
    -77.0065,
    "Washington Union Station",
  ],
  [
    "Chicago Union Station",
    "Chicago",
    "United States",
    41.8786,
    -87.6398,
    "Chicago Union Station",
  ],
  [
    "Los Angeles Union Station",
    "Los Angeles",
    "United States",
    34.056,
    -118.2368,
    "Union Station (Los Angeles)",
  ],
  [
    "Toronto Union Station",
    "Toronto",
    "Canada",
    43.6453,
    -79.3806,
    "Union Station (Toronto)",
  ],
  [
    "Central Station",
    "Sydney",
    "Australia",
    -33.883,
    151.2069,
    "Central railway station, Sydney",
  ],
].map(
  ([name, city, country, lat, lng, wiki]) =>
    ({
      kind: "station",
      name,
      city,
      country,
      lat,
      lng,
      wiki,
    }) as TransportPoint,
)

const PORTS: TransportPoint[] = [
  ["Port of Shanghai", "Shanghai", "China", 31.34, 121.5, "Port of Shanghai"],
  [
    "Port of Ningbo-Zhoushan",
    "Ningbo",
    "China",
    29.8683,
    121.544,
    "Port of Ningbo-Zhoushan",
  ],
  ["Port of Shenzhen", "Shenzhen", "China", 22.49, 113.88, "Port of Shenzhen"],
  [
    "Port of Guangzhou",
    "Guangzhou",
    "China",
    23.096,
    113.436,
    "Port of Guangzhou",
  ],
  ["Port of Qingdao", "Qingdao", "China", 36.083, 120.317, "Port of Qingdao"],
  ["Port of Tianjin", "Tianjin", "China", 38.987, 117.777, "Port of Tianjin"],
  ["Port of Xiamen", "Xiamen", "China", 24.448, 118.068, "Port of Xiamen"],
  ["Port of Dalian", "Dalian", "China", 38.946, 121.658, "Port of Dalian"],
  [
    "Port of Hong Kong",
    "Hong Kong",
    "Hong Kong",
    22.32,
    114.12,
    "Port of Hong Kong",
  ],
  [
    "Port of Kaohsiung",
    "Kaohsiung",
    "Taiwan",
    22.615,
    120.281,
    "Port of Kaohsiung",
  ],
  [
    "Port of Singapore",
    "Singapore",
    "Singapore",
    1.2644,
    103.82,
    "Port of Singapore",
  ],
  ["Port Klang", "Klang", "Malaysia", 3.0, 101.392, "Port Klang"],
  [
    "Tanjung Pelepas",
    "Johor",
    "Malaysia",
    1.36,
    103.55,
    "Port of Tanjung Pelepas",
  ],
  [
    "Laem Chabang",
    "Chonburi",
    "Thailand",
    13.082,
    100.883,
    "Laem Chabang Port",
  ],
  [
    "Tanjung Priok",
    "Jakarta",
    "Indonesia",
    -6.105,
    106.881,
    "Tanjung Priok Port",
  ],
  ["Port of Busan", "Busan", "South Korea", 35.1028, 129.0403, "Port of Busan"],
  ["Port of Tokyo", "Tokyo", "Japan", 35.61, 139.77, "Port of Tokyo"],
  [
    "Port of Yokohama",
    "Yokohama",
    "Japan",
    35.454,
    139.668,
    "Port of Yokohama",
  ],
  ["Port of Kobe", "Kobe", "Japan", 34.672, 135.21, "Port of Kobe"],
  ["Port of Nagoya", "Nagoya", "Japan", 35.09, 136.88, "Port of Nagoya"],
  [
    "Jawaharlal Nehru Port",
    "Navi Mumbai",
    "India",
    18.949,
    72.951,
    "Jawaharlal Nehru Port",
  ],
  ["Mundra Port", "Mundra", "India", 22.739, 69.704, "Mundra Port"],
  ["Port of Colombo", "Colombo", "Sri Lanka", 6.95, 79.84, "Port of Colombo"],
  [
    "Jebel Ali",
    "Dubai",
    "United Arab Emirates",
    25.01,
    55.06,
    "Port of Jebel Ali",
  ],
  [
    "Khalifa Port",
    "Abu Dhabi",
    "United Arab Emirates",
    24.8,
    54.64,
    "Khalifa Port",
  ],
  [
    "Jeddah Islamic Port",
    "Jeddah",
    "Saudi Arabia",
    21.45,
    39.15,
    "Jeddah Islamic Port",
  ],
  ["Port of Salalah", "Salalah", "Oman", 16.94, 54.0, "Port of Salalah"],
  [
    "Port of Rotterdam",
    "Rotterdam",
    "Netherlands",
    51.9496,
    4.1396,
    "Port of Rotterdam",
  ],
  [
    "Port of Antwerp",
    "Antwerp",
    "Belgium",
    51.27,
    4.38,
    "Port of Antwerp-Bruges",
  ],
  ["Port of Hamburg", "Hamburg", "Germany", 53.54, 9.93, "Port of Hamburg"],
  [
    "Port of Felixstowe",
    "Felixstowe",
    "United Kingdom",
    51.954,
    1.311,
    "Port of Felixstowe",
  ],
  [
    "Port of Southampton",
    "Southampton",
    "United Kingdom",
    50.895,
    -1.416,
    "Port of Southampton",
  ],
  ["Port of Le Havre", "Le Havre", "France", 49.472, 0.108, "Port of Le Havre"],
  [
    "Port of Marseille",
    "Marseille",
    "France",
    43.34,
    5.33,
    "Port of Marseille",
  ],
  [
    "Port of Algeciras",
    "Algeciras",
    "Spain",
    36.133,
    -5.436,
    "Port of Algeciras",
  ],
  ["Port of Valencia", "Valencia", "Spain", 39.444, -0.316, "Port of Valencia"],
  [
    "Port of Barcelona",
    "Barcelona",
    "Spain",
    41.345,
    2.166,
    "Port of Barcelona",
  ],
  ["Port of Genoa", "Genoa", "Italy", 44.405, 8.92, "Port of Genoa"],
  [
    "Port of Gioia Tauro",
    "Gioia Tauro",
    "Italy",
    38.43,
    15.9,
    "Port of Gioia Tauro",
  ],
  ["Port of Piraeus", "Athens", "Greece", 37.942, 23.646, "Port of Piraeus"],
  ["Port of Gdańsk", "Gdańsk", "Poland", 54.403, 18.677, "Port of Gdańsk"],
  ["Tanger Med", "Tangier", "Morocco", 35.884, -5.5, "Tanger Med"],
  ["Port of Durban", "Durban", "South Africa", -29.87, 31.03, "Port of Durban"],
  [
    "Port of Los Angeles",
    "Los Angeles",
    "United States",
    33.7406,
    -118.2706,
    "Port of Los Angeles",
  ],
  [
    "Port of Long Beach",
    "Long Beach",
    "United States",
    33.755,
    -118.216,
    "Port of Long Beach",
  ],
  [
    "Port of New York and New Jersey",
    "New York",
    "United States",
    40.67,
    -74.05,
    "Port of New York and New Jersey",
  ],
  [
    "Port of Savannah",
    "Savannah",
    "United States",
    32.13,
    -81.145,
    "Port of Savannah",
  ],
  [
    "Port of Houston",
    "Houston",
    "United States",
    29.725,
    -95.223,
    "Port of Houston",
  ],
  [
    "Port of Oakland",
    "Oakland",
    "United States",
    37.795,
    -122.289,
    "Port of Oakland",
  ],
  [
    "Port of Seattle",
    "Seattle",
    "United States",
    47.6,
    -122.34,
    "Port of Seattle",
  ],
  [
    "Port of Vancouver",
    "Vancouver",
    "Canada",
    49.29,
    -123.1,
    "Port of Vancouver",
  ],
  ["Port of Santos", "Santos", "Brazil", -23.987, -46.292, "Port of Santos"],
  ["Port of Callao", "Callao", "Peru", -12.05, -77.14, "Port of Callao"],
  ["Balboa", "Panama City", "Panama", 8.95, -79.565, "Port of Balboa"],
  [
    "Port Botany",
    "Sydney",
    "Australia",
    -33.97,
    151.23,
    "Port Botany (seaport)",
  ],
  [
    "Port of Melbourne",
    "Melbourne",
    "Australia",
    -37.83,
    144.92,
    "Port of Melbourne",
  ],
].map(
  ([name, city, country, lat, lng, wiki]) =>
    ({
      kind: "port",
      name,
      city,
      country,
      lat,
      lng,
      wiki,
    }) as TransportPoint,
)

export type LayerDef = {
  id: LayerId
  label: string
  kind: TransportKind
  color: string
  data: TransportPoint[]
}

export const LAYERS: LayerDef[] = [
  {
    id: "airports",
    label: "Airports",
    kind: "airport",
    color: "#5fb0ff",
    data: AIRPORTS,
  },
  {
    id: "stations",
    label: "Train stations",
    kind: "station",
    color: "#7be0a3",
    data: STATIONS,
  },
  { id: "ports", label: "Ports", kind: "port", color: "#ffd166", data: PORTS },
]

export const KIND_COLOR: Record<TransportKind, string> = {
  airport: "#5fb0ff",
  station: "#7be0a3",
  port: "#ffd166",
}

export const KIND_ICON: Record<TransportKind, string> = {
  airport: "✈",
  station: "🚆",
  port: "⚓",
}
