// Curated travel-gateway layers — major airports, train stations and seaports.
// These are discovery aids ("where can I travel to/from here?"), so the lists
// are the world's principal hubs rather than exhaustive registries: a curated
// static set keeps the app offline-capable and keeps the globe's frame budget
// safe (the layers are off by default and only a few dozen points each).
//
// Each point carries an explicit `wiki` article title: many hubs are named
// after people (Jomo Kenyatta, O. R. Tambo, Mohammed V…), so fetching by the
// short display name would surface the person's article, not the airport's.
export type TransportKind = "airport" | "station" | "port"
export type LayerId = "airports" | "stations" | "ports"

export type TransportPoint = {
  kind: TransportKind
  name: string
  code?: string // IATA for airports; many stations/ports have none
  city: string
  country: string
  lat: number
  lng: number
  wiki: string // exact Wikipedia article title
}

const AIRPORTS: TransportPoint[] = [
  [
    "Hartsfield–Jackson Atlanta",
    "ATL",
    "Atlanta",
    "United States",
    33.6407,
    -84.4277,
    "Hartsfield–Jackson Atlanta International Airport",
  ],
  [
    "Beijing Capital",
    "PEK",
    "Beijing",
    "China",
    40.0799,
    116.6031,
    "Beijing Capital International Airport",
  ],
  [
    "Dubai International",
    "DXB",
    "Dubai",
    "United Arab Emirates",
    25.2532,
    55.3657,
    "Dubai International Airport",
  ],
  [
    "Los Angeles International",
    "LAX",
    "Los Angeles",
    "United States",
    33.9416,
    -118.4085,
    "Los Angeles International Airport",
  ],
  [
    "Tokyo Haneda",
    "HND",
    "Tokyo",
    "Japan",
    35.5494,
    139.7798,
    "Haneda Airport",
  ],
  [
    "O'Hare International",
    "ORD",
    "Chicago",
    "United States",
    41.9742,
    -87.9073,
    "O'Hare International Airport",
  ],
  [
    "London Heathrow",
    "LHR",
    "London",
    "United Kingdom",
    51.47,
    -0.4543,
    "Heathrow Airport",
  ],
  [
    "Paris Charles de Gaulle",
    "CDG",
    "Paris",
    "France",
    49.0097,
    2.5479,
    "Charles de Gaulle Airport",
  ],
  [
    "Amsterdam Schiphol",
    "AMS",
    "Amsterdam",
    "Netherlands",
    52.3105,
    4.7683,
    "Amsterdam Airport Schiphol",
  ],
  [
    "Frankfurt",
    "FRA",
    "Frankfurt",
    "Germany",
    50.0379,
    8.5622,
    "Frankfurt Airport",
  ],
  [
    "Istanbul",
    "IST",
    "Istanbul",
    "Turkey",
    41.2753,
    28.7519,
    "Istanbul Airport",
  ],
  [
    "Singapore Changi",
    "SIN",
    "Singapore",
    "Singapore",
    1.3644,
    103.9915,
    "Singapore Changi Airport",
  ],
  [
    "Seoul Incheon",
    "ICN",
    "Seoul",
    "South Korea",
    37.4602,
    126.4407,
    "Incheon International Airport",
  ],
  [
    "Hong Kong International",
    "HKG",
    "Hong Kong",
    "Hong Kong",
    22.308,
    113.9185,
    "Hong Kong International Airport",
  ],
  [
    "Shanghai Pudong",
    "PVG",
    "Shanghai",
    "China",
    31.1443,
    121.8083,
    "Shanghai Pudong International Airport",
  ],
  [
    "Madrid Barajas",
    "MAD",
    "Madrid",
    "Spain",
    40.4983,
    -3.5676,
    "Adolfo Suárez Madrid–Barajas Airport",
  ],
  [
    "Suvarnabhumi",
    "BKK",
    "Bangkok",
    "Thailand",
    13.69,
    100.7501,
    "Suvarnabhumi Airport",
  ],
  [
    "New York JFK",
    "JFK",
    "New York",
    "United States",
    40.6413,
    -73.7781,
    "John F. Kennedy International Airport",
  ],
  [
    "Indira Gandhi International",
    "DEL",
    "Delhi",
    "India",
    28.5562,
    77.1,
    "Indira Gandhi International Airport",
  ],
  [
    "Sydney Kingsford Smith",
    "SYD",
    "Sydney",
    "Australia",
    -33.9399,
    151.1753,
    "Sydney Airport",
  ],
  [
    "San Francisco International",
    "SFO",
    "San Francisco",
    "United States",
    37.6213,
    -122.379,
    "San Francisco International Airport",
  ],
  [
    "Toronto Pearson",
    "YYZ",
    "Toronto",
    "Canada",
    43.6777,
    -79.6248,
    "Toronto Pearson International Airport",
  ],
  [
    "Hamad International",
    "DOH",
    "Doha",
    "Qatar",
    25.2731,
    51.608,
    "Hamad International Airport",
  ],
  ["Munich", "MUC", "Munich", "Germany", 48.3538, 11.7861, "Munich Airport"],
  [
    "Barcelona–El Prat",
    "BCN",
    "Barcelona",
    "Spain",
    41.2974,
    2.0833,
    "Josep Tarradellas Barcelona–El Prat Airport",
  ],
  [
    "Rome Fiumicino",
    "FCO",
    "Rome",
    "Italy",
    41.8003,
    12.2389,
    "Leonardo da Vinci International Airport",
  ],
  [
    "São Paulo Guarulhos",
    "GRU",
    "São Paulo",
    "Brazil",
    -23.4356,
    -46.4731,
    "São Paulo–Guarulhos International Airport",
  ],
  [
    "Mexico City International",
    "MEX",
    "Mexico City",
    "Mexico",
    19.4361,
    -99.0719,
    "Mexico City International Airport",
  ],
  [
    "O. R. Tambo",
    "JNB",
    "Johannesburg",
    "South Africa",
    -26.1392,
    28.246,
    "O. R. Tambo International Airport",
  ],
  [
    "Cairo International",
    "CAI",
    "Cairo",
    "Egypt",
    30.1219,
    31.4056,
    "Cairo International Airport",
  ],
  [
    "Sheremetyevo",
    "SVO",
    "Moscow",
    "Russia",
    55.9726,
    37.4146,
    "Sheremetyevo International Airport",
  ],
  [
    "Kuala Lumpur International",
    "KUL",
    "Kuala Lumpur",
    "Malaysia",
    2.7456,
    101.7099,
    "Kuala Lumpur International Airport",
  ],
  [
    "Soekarno–Hatta",
    "CGK",
    "Jakarta",
    "Indonesia",
    -6.1256,
    106.6559,
    "Soekarno–Hatta International Airport",
  ],
  [
    "Chhatrapati Shivaji Maharaj",
    "BOM",
    "Mumbai",
    "India",
    19.0896,
    72.8656,
    "Chhatrapati Shivaji Maharaj International Airport",
  ],
  [
    "Miami International",
    "MIA",
    "Miami",
    "United States",
    25.7959,
    -80.287,
    "Miami International Airport",
  ],
  [
    "Vancouver International",
    "YVR",
    "Vancouver",
    "Canada",
    49.1967,
    -123.1815,
    "Vancouver International Airport",
  ],
  ["Zürich", "ZRH", "Zurich", "Switzerland", 47.4582, 8.5555, "Zurich Airport"],
  [
    "Copenhagen",
    "CPH",
    "Copenhagen",
    "Denmark",
    55.618,
    12.6508,
    "Copenhagen Airport",
  ],
  [
    "Helsinki-Vantaa",
    "HEL",
    "Helsinki",
    "Finland",
    60.3172,
    24.9633,
    "Helsinki Airport",
  ],
  ["Lisbon", "LIS", "Lisbon", "Portugal", 38.7742, -9.1342, "Lisbon Airport"],
  [
    "Auckland",
    "AKL",
    "Auckland",
    "New Zealand",
    -37.0082,
    174.785,
    "Auckland Airport",
  ],
  [
    "Ezeiza",
    "EZE",
    "Buenos Aires",
    "Argentina",
    -34.8222,
    -58.5358,
    "Ministro Pistarini International Airport",
  ],
  [
    "Addis Ababa Bole",
    "ADD",
    "Addis Ababa",
    "Ethiopia",
    8.9779,
    38.7993,
    "Addis Ababa Bole International Airport",
  ],
  [
    "Jomo Kenyatta",
    "NBO",
    "Nairobi",
    "Kenya",
    -1.3192,
    36.9278,
    "Jomo Kenyatta International Airport",
  ],
  [
    "Mohammed V",
    "CMN",
    "Casablanca",
    "Morocco",
    33.3675,
    -7.5899,
    "Mohammed V International Airport",
  ],
].map(
  ([name, code, city, country, lat, lng, wiki]) =>
    ({
      kind: "airport",
      name,
      code,
      city,
      country,
      lat,
      lng,
      wiki,
    }) as TransportPoint,
)

const STATIONS: TransportPoint[] = [
  ["Gare du Nord", "Paris", "France", 48.8809, 2.3553, "Gare du Nord"],
  [
    "St Pancras International",
    "London",
    "United Kingdom",
    51.532,
    -0.1264,
    "St Pancras railway station",
  ],
  [
    "King's Cross",
    "London",
    "United Kingdom",
    51.5308,
    -0.1238,
    "London King's Cross railway station",
  ],
  [
    "Grand Central Terminal",
    "New York",
    "United States",
    40.7527,
    -73.9772,
    "Grand Central Terminal",
  ],
  ["Tokyo Station", "Tokyo", "Japan", 35.6812, 139.7671, "Tokyo Station"],
  ["Shinjuku Station", "Tokyo", "Japan", 35.6896, 139.7006, "Shinjuku Station"],
  [
    "Berlin Hauptbahnhof",
    "Berlin",
    "Germany",
    52.5251,
    13.3694,
    "Berlin Hauptbahnhof",
  ],
  [
    "Frankfurt Hauptbahnhof",
    "Frankfurt",
    "Germany",
    50.107,
    8.6638,
    "Frankfurt (Main) Hauptbahnhof",
  ],
  [
    "Roma Termini",
    "Rome",
    "Italy",
    41.9009,
    12.5018,
    "Roma Termini railway station",
  ],
  [
    "Madrid Atocha",
    "Madrid",
    "Spain",
    40.4068,
    -3.6895,
    "Madrid Atocha railway station",
  ],
  [
    "Barcelona Sants",
    "Barcelona",
    "Spain",
    41.3792,
    2.1402,
    "Barcelona Sants railway station",
  ],
  [
    "Amsterdam Centraal",
    "Amsterdam",
    "Netherlands",
    52.3791,
    4.9003,
    "Amsterdam Centraal station",
  ],
  [
    "Zürich Hauptbahnhof",
    "Zurich",
    "Switzerland",
    47.3779,
    8.5403,
    "Zürich Hauptbahnhof",
  ],
  ["Gare de Lyon", "Paris", "France", 48.8443, 2.3744, "Gare de Lyon"],
  [
    "Milano Centrale",
    "Milan",
    "Italy",
    45.4869,
    9.2042,
    "Milano Centrale railway station",
  ],
  [
    "Wien Hauptbahnhof",
    "Vienna",
    "Austria",
    48.185,
    16.3754,
    "Wien Hauptbahnhof",
  ],
  [
    "Beijing South",
    "Beijing",
    "China",
    39.865,
    116.3786,
    "Beijing South railway station",
  ],
  [
    "Shanghai Hongqiao",
    "Shanghai",
    "China",
    31.1943,
    121.3203,
    "Shanghai Hongqiao railway station",
  ],
  ["Seoul Station", "Seoul", "South Korea", 37.5559, 126.9723, "Seoul Station"],
  [
    "Bruxelles-Central",
    "Brussels",
    "Belgium",
    50.8456,
    4.3571,
    "Brussels-Central railway station",
  ],
  [
    "Union Station",
    "Washington, D.C.",
    "United States",
    38.8977,
    -77.0065,
    "Washington Union Station",
  ],
  [
    "Howrah Junction",
    "Kolkata",
    "India",
    22.5839,
    88.3425,
    "Howrah Junction railway station",
  ],
  [
    "Chhatrapati Shivaji Terminus",
    "Mumbai",
    "India",
    18.9398,
    72.8355,
    "Chhatrapati Shivaji Maharaj Terminus",
  ],
  [
    "Central Station",
    "Sydney",
    "Australia",
    -33.883,
    151.2069,
    "Central railway station, Sydney",
  ],
  [
    "München Hauptbahnhof",
    "Munich",
    "Germany",
    48.1402,
    11.5586,
    "München Hauptbahnhof",
  ],
  [
    "Lyon Part-Dieu",
    "Lyon",
    "France",
    45.7605,
    4.8595,
    "Lyon-Part-Dieu station",
  ],
].map(
  ([name, city, country, lat, lng, wiki]) =>
    ({
      kind: "station",
      name,
      city,
      country,
      lat,
      lng,
      wiki,
    }) as TransportPoint,
)

const PORTS: TransportPoint[] = [
  ["Port of Shanghai", "Shanghai", "China", 31.34, 121.5, "Port of Shanghai"],
  [
    "Port of Singapore",
    "Singapore",
    "Singapore",
    1.2644,
    103.82,
    "Port of Singapore",
  ],
  [
    "Port of Ningbo-Zhoushan",
    "Ningbo",
    "China",
    29.8683,
    121.544,
    "Port of Ningbo-Zhoushan",
  ],
  [
    "Port of Rotterdam",
    "Rotterdam",
    "Netherlands",
    51.9496,
    4.1396,
    "Port of Rotterdam",
  ],
  ["Port of Busan", "Busan", "South Korea", 35.1028, 129.0403, "Port of Busan"],
  [
    "Port of Hong Kong",
    "Hong Kong",
    "Hong Kong",
    22.32,
    114.12,
    "Port of Hong Kong",
  ],
  [
    "Port of Antwerp",
    "Antwerp",
    "Belgium",
    51.27,
    4.38,
    "Port of Antwerp-Bruges",
  ],
  ["Port of Hamburg", "Hamburg", "Germany", 53.54, 9.93, "Port of Hamburg"],
  [
    "Port of Los Angeles",
    "Los Angeles",
    "United States",
    33.7406,
    -118.2706,
    "Port of Los Angeles",
  ],
  [
    "Port of Long Beach",
    "Long Beach",
    "United States",
    33.755,
    -118.216,
    "Port of Long Beach",
  ],
  [
    "Jebel Ali",
    "Dubai",
    "United Arab Emirates",
    25.01,
    55.06,
    "Port of Jebel Ali",
  ],
  [
    "Port of New York and New Jersey",
    "New York",
    "United States",
    40.67,
    -74.05,
    "Port of New York and New Jersey",
  ],
  ["Port of Valencia", "Valencia", "Spain", 39.444, -0.316, "Port of Valencia"],
  ["Port of Piraeus", "Athens", "Greece", 37.942, 23.646, "Port of Piraeus"],
  [
    "Port of Felixstowe",
    "Felixstowe",
    "United Kingdom",
    51.954,
    1.311,
    "Port of Felixstowe",
  ],
  ["Port of Santos", "Santos", "Brazil", -23.987, -46.292, "Port of Santos"],
  ["Port of Tokyo", "Tokyo", "Japan", 35.61, 139.77, "Port of Tokyo"],
  [
    "Port Botany",
    "Sydney",
    "Australia",
    -33.97,
    151.23,
    "Port Botany (seaport)",
  ],
  ["Port of Colombo", "Colombo", "Sri Lanka", 6.95, 79.84, "Port of Colombo"],
  ["Port of Durban", "Durban", "South Africa", -29.87, 31.03, "Port of Durban"],
  [
    "Tanjung Pelepas",
    "Johor",
    "Malaysia",
    1.36,
    103.55,
    "Port of Tanjung Pelepas",
  ],
  ["Port of Genoa", "Genoa", "Italy", 44.405, 8.92, "Port of Genoa"],
  [
    "Port of Marseille",
    "Marseille",
    "France",
    43.34,
    5.33,
    "Port of Marseille",
  ],
  [
    "Port of Vancouver",
    "Vancouver",
    "Canada",
    49.29,
    -123.1,
    "Port of Vancouver",
  ],
  [
    "Port of Seattle",
    "Seattle",
    "United States",
    47.6,
    -122.34,
    "Port of Seattle",
  ],
].map(
  ([name, city, country, lat, lng, wiki]) =>
    ({
      kind: "port",
      name,
      city,
      country,
      lat,
      lng,
      wiki,
    }) as TransportPoint,
)

export type LayerDef = {
  id: LayerId
  label: string
  kind: TransportKind
  color: string
  data: TransportPoint[]
}

export const LAYERS: LayerDef[] = [
  {
    id: "airports",
    label: "Airports",
    kind: "airport",
    color: "#5fb0ff",
    data: AIRPORTS,
  },
  {
    id: "stations",
    label: "Train stations",
    kind: "station",
    color: "#7be0a3",
    data: STATIONS,
  },
  { id: "ports", label: "Ports", kind: "port", color: "#ffd166", data: PORTS },
]

export const KIND_COLOR: Record<TransportKind, string> = {
  airport: "#5fb0ff",
  station: "#7be0a3",
  port: "#ffd166",
}

export const KIND_ICON: Record<TransportKind, string> = {
  airport: "✈",
  station: "🚆",
  port: "⚓",
}
